apiVersion: v1
kind: Service
metadata:
 name: filemanager-entrypoint
 namespace: default
spec:
 type: NodePort
 selector:
  app: filemanager
 ports:
 - port: 15000
   targetPort: 15000
   nodePort: 31083
 externalTrafficPolicy: Cluster
