apiVersion: apps/v1
kind: Deployment
metadata:
 name: filemanager
 namespace: default
spec:
 replicas: 2
 selector:
  matchLabels:
   app: filemanager
 template:
  metadata:
   labels:
    app: filemanager
  spec:
   containers:
   - name: filemanager
     image: docker.io/iliketheoranges/filemanager:0.2
     volumeMounts:
     - mountPath: /dirprueba
       name: dirprueba
   nodeSelector: 
     NAME: fileManager
   volumes:
   - name: dirprueba
     hostPath:
      path: /home/ubuntu/practica2/fileManager/dirprueba
      type: Directory
     